[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/web/index.html"
healthcheckTimeout = 120
restartPolicyType = "ALWAYS"
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
